// ID: 389

// Description:
// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

// Solution:

// 0 ^ a ^ a ^ b ^ b ^ ... ^ iso_element = 0 ^ iso_element = iso_element
class Solution {
public:
    char findTheDifference(string s, string t) {
        char ans = 0;
        for(auto c : s) ans ^= c;
        for(auto c : t) ans ^= c;
        return ans;
    }
};